name: Demo CI/CD Pipeline

on: [push] #merge some

jobs:
  build:
    runs-on: ubuntu-latest #another OS systems 
    steps:
    - uses: actions/checkout@v3
    - name: Run a simple echo command
      run: echo "Hello Datadog! CI/CD pipeline successfully triggered!"
